import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Cairo } from "next/font/google";
import { getLocale, getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "next-themes"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ['arabic'],
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Settings",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} dir={locale === 'ar' ? "rtl" : "ltr"} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cairo.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            storageKey='settings-app'
          >
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
